[2025-05-31T16:48:49.779Z]  @firebase/firestore: Firestore (11.8.0): WebChannelConnection RPC 'Listen' stream 0x6fd129f1 transport errored. Name: undefined Message: undefined
firestore.googleapis…e&zx=z2jdqnpqa07e:1
 Failed to load resource: the server responded with a status of 400 ()
firestore.googleapis…=fultuho36jqn&t=1:1
 Failed to load resource: the server responded with a status of 400 ()
 [2025-05-31T16:48:59.527Z]  @firebase/firestore: Firestore (11.8.0): WebChannelConnection RPC 'Listen' stream 0x6fd129f3 transport errored. Name: undefined Message: undefined
firestore.googleapis…=rher71t12d6e&t=1:1
 Failed to load resource: the server responded with a status of 400 ()
 [2025-05-31T16:49:05.070Z]  @firebase/firestore: Firestore (11.8.0): WebChannelConnection RPC 'Listen' stream 0x6fd129f4 transport errored. Name: undefined Message: undefined
firestore.googleapis…=tnd6zjvxgguc&t=1:1
 Failed to load resource: the server responded with a status of 400 ()
 [2025-05-31T16:49:13.817Z]  @firebase/firestore: Firestore (11.8.0): WebChannelConnection RPC 'Listen' stream 0x6fd129f5 transport errored. Name: undefined Message: undefined
 Error fetching user preferences from Firestore: FirebaseError: [code=unavailable]: Failed to get document because the client is offline.
6000-firebase-studio…inal-stack-frames:1
 Failed to load resource: the server responded with a status of 403 ()
 WebSocket connection to 'wss://6000-firebase-studio-1748064333696.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/webpack-hmr' failed:
firebase.ts:34 Firebase auth persistence set to browserLocalPersistence.
warn-once.js:16 Image with src "https://placehold.co/500x350.png" has "fill" but is missing "sizes" prop. Please add it to improve page performance. Read more: https://nextjs.org/docs/api-reference/next/image#sizes
use-websocket.js:42 WebSocket connection to 'wss://6000-firebase-studio-1748064333696.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/webpack-hmr' failed:
LoginPage.tsx:22 LoginPage: Attempting signInWithPopup...
LoginPage.tsx:24 LoginPage: signInWithPopup successful, user:
UserImpl
localhost:5001/api/u…TVWWZHAwDfbDozVN2:1
 Failed to load resource: net::ERR_CONNECTION_REFUSED
intercept-console-error.js:50 Error in fetchUserFromMongo: TypeError: Failed to fetch
    at fetchUserFromMongo (page.tsx:62:30)
    at AppContent.useEffect.unsubscribe [as next] (page.tsx:129:38)